// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback allows `prisma generate` on CI/Vercel before DATABASE_URL is wired up.
    url: process.env.DATABASE_URL ?? "postgresql://localhost:5432/phonefarm",
  },
});
